CREATE TABLE [dbo].[Service]
(
	[NomorNota] INT NOT NULL PRIMARY KEY,
	[Tanggal] DATETIME2 NOT NULL,
	[NamaPelanggan] NVARCHAR(50) NOT NULL, 
    [NoHp] VARCHAR(12) NULL, 
    [TipeHp] NVARCHAR(50) NOT NULL, 
    [Imei] VARCHAR(4) NULL, 
    [Kerusakan] NVARCHAR(256) NOT NULL, 
    [YangBelumDicek] NVARCHAR(50) NULL, 
    [Kelengkapan] VARCHAR(50) NULL, 
    [Warna] VARCHAR(50) NULL, 
    [KataSandiPola] VARCHAR(50) NULL, 
    [Teknisi] NVARCHAR(50) NULL, 
    [StatusServisan] VARCHAR(50) NULL, 
    [TanggalKonfirmasi] DATETIME2 NULL, 
    [IsiKonfirmasi] NVARCHAR(256) NULL, 
    [Biaya] MONEY NULL, 
    [Discount] INT NULL, 
    [Dp] MONEY NULL,
    [TambahanBiaya] MONEY NULL, 
    [TotalBiaya] MONEY NULL, 
    [HargaSparepart] MONEY NULL, 
    [Sisa] MONEY NULL, 
    [LabaRugi] MONEY NULL, 
    [TanggalPengambilan] DATETIME2 NULL,
)
