CREATE TABLE [dbo].[Service]
(
	[NomorNota] INT NOT NULL PRIMARY KEY,
	[Tanggal] DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	[NamaPelanggan] NVARCHAR(50) NOT NULL, 
    [NoHp] VARCHAR(12) NULL, 
    [TipeHp] NVARCHAR(50) NOT NULL, 
    [Imei] VARCHAR(4) NULL, 
    [DamageId] int NOT NULL, 
    [YangBelumDicek] NVARCHAR(50) NULL, 
    [Kelengkapan] VARCHAR(50) NULL,
    [Warna] VARCHAR(50) NULL, 
    [KataSandiPola] VARCHAR(50) NULL, 
    [TechnicianId] int NULL, 
    [StatusServisan] VARCHAR(50) NULL, 
    [TanggalKonfirmasi] DATETIME2 NULL, 
    [IsiKonfirmasi] NVARCHAR(256) NULL, 
    [Biaya] DECIMAL(19, 4) NULL, 
    [Discount] INT NULL, 
    [Dp] DECIMAL(19, 4) NULL,
    [TambahanBiaya] DECIMAL(19, 4) NULL, 
    [TotalBiaya] DECIMAL(19, 4) NULL, 
    [HargaSparepart] DECIMAL(19, 4) NULL, 
    [Sisa] DECIMAL(19, 4) NULL, 
    [LabaRugi] DECIMAL(19, 4) NULL, 
    [TanggalPengambilan] DATETIME2 NULL, 
    CONSTRAINT [FK_Service_ToTechnician] FOREIGN KEY ([TechnicianId]) REFERENCES [Technician]([Id]), 
    CONSTRAINT [FK_Service_ToDamage] FOREIGN KEY ([DamageId]) REFERENCES [Damage]([Id]),
)
